### ISSUE TITLE
Option to over ride title

### ISSUE THREAD

**Issue by atulmy** [editor-js/attaches#16]
Is it possible to over ride `title: 'Attaches'` which is shown on hover of icon inside editor?
```javascript
static get toolbox() {
  return {
    icon: Icon,
    title: 'Attaches'
  };
}
```

**Comment by neSpecc** [comment]
Yes, you can override the `toolbox` via [EditorConfig](https://editorjs.io/getting-started#available-tools-options), or using the [i18n options](https://editorjs.io/i18n).

**Comment by RafaelRViana** [comment]
Could you give one example how would it be set?
