### ISSUE TITLE
Additional Headers

### ISSUE THREAD

**Issue by artsur** [editor-js/attaches#23]
It would be nice to add the ability to send additional headers
For example: X-CSRF-TOKEN

Just like it is available in image https://github.com/editor-js/image/blob/master/src/uploader.js
Line #L64

**Comment by DarkZeus** [comment]
This is a very necessary feature, I wonder why the devs didn't made this from the very beginning like they made with the image plugin and why are they so slow with PRs.

**Comment by jere-co** [comment]
There's already a pull request for this https://github.com/editor-js/attaches/pull/24

No idea why it is taking so long to accept it though. Desperately needing it myself too.

**Comment by ybenitezf** [comment]
+1

**Comment by artsur** [comment]
There are errors with npm run build. Trying to resolve.....
```
   ERROR in ./src/index.js
   Module build failed (from ./node_modules/eslint-loader/index.js):
   Error: .eslintrc » eslint-config-codex » eslint-config-standard:
        Environment key "es2021" is unknown
```

**Comment by artsur** [comment]
with ``yarn run build`` we have errors too
