### ISSUE TITLE
[bug] Uncaught TypeError: Cannot set property 'dropTarget' of undefined

### ISSUE THREAD

**Issue by robonetphy** [editor-js/attaches#33]
Steps To regenerate:

- Create `attache` block
- Upload any file.
- After successful upload press the `Enter` key.

Video Sample:

https://user-images.githubusercontent.com/23169768/118863323-6292f680-b8fc-11eb-8795-68ed3646ce58.mp4

**Comment by neSpecc** [comment]
Looks like there is an issue with styles loading on your side.

I'll close it for now. If someone will meet same problem, I'll reopen.
