### ISSUE TITLE
Not supported in editor Js read-only mode

### ISSUE THREAD

**Issue by osain-az** [editor-js/attaches#36]
Hello, i am using attaches plugin for my  project and it works fine but when the editor js is in read-only mode, i got an Error. When debugging  i got this  `index.js:1 Editor.js is not ready because of Error: To enable read-only mode all connected tools should support it. Tools attached don't support read-only mode.`.

Is their a way to enable support for read-only mode or suggestion on how to handle this

**Comment by mzaksana** [comment]
Don't know why, attachments should have a read-only mode. Just like the other tools `things`  (egs [quote](https://github.com/editor-js/quote/blob/d781cd0d5c7529930440c254f0146ce5db63f9f8/src/index.js#L30-L32)), to make it work with editorjs read-only configuration.

May this help until future update, maybe. Based on pr https://github.com/editor-js/attaches/pull/17,  we can force `read-only mode` like : 
```typescript
    import Attaches from "@editorjs/attaches"
    Attaches.isReadOnlySupported = () => {return true}
```
> Note : **_no responsibility disclaimer_** 🤡
