### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by dhanush-tydy** [editor-js/attaches#48]

**Comment by neSpecc** [comment]
No description provided.

**Comment by dhanush-tydy** [comment]
When i try to upload file it's throwing error as mentioned

**Comment by dhanush-tydy** [comment]
> No description provided.

When i try to upload file it's throwing error as Cannot read property 'split' of undefined

**Comment by 4KDA** [comment]
Same problem

**Comment by 4KDA** [comment]
Adding 'title' field to file helps
https://github.com/editor-js/attaches/issues/42

> {
        success: 1,
        file: {
          url: 'https://www.tesla.com/tesla_theme/assets/img/_vehicle_redesign/roadster_and_semi/roadster/hero.jpg',
          size: 91,
          name: 'hero.jpg',
          extension: 'jpg',
          title: 'Hero',
        }
