### ISSUE TITLE
Getting error: "File upload failed" for no reason

### ISSUE THREAD

**Issue by Stelikas** [editor-js/attaches#56]
The uploading works fine, the response is also correct, the file gets displayed in the builder although without the file name for some reason. 

### Editorjs config: 

          attaches: {
                  class: AttachesTool,
                  config: {
                      additionalRequestHeaders: {
                          "X-CSRF-TOKEN": this.token,
                      },
                      endpoint: '/admin/builder/upload-file',
                  }
              },

### Laravel Controller: 

              public function upload_file() {
                  if (request()->file('file')) {
                     
                      $file = request()->file('file');
          
                      $extension = $file->extension();
          
                      $size = $file->getSize();
          
                      $fileName = $file->getClientOriginalName();
          
                      $time = date('H-i-s');
          
                      $date = date('d-m-Y');
          
                      Storage::disk('public')->put('uploads/categories/'.$date.'/'.$time.'_'.$fileName, file_get_contents($file));
          
                      return response()->json([
                          'success' => 1, 
                          'file' => [
                              'url' => asset('/storage/uploads/categories/'.$date.'/'.$time.'_'.$fileName),
                              'size' => $size,
                              'extension' => $extension,
                              'name' => $fileName
                          ]
                      ], 200);
                  }
              }

### Result: 

Getting "File Upload Failed" although it is uploaded and the file is displayed in the builder but without the file name.

**Comment by Wradgio** [comment]
Same issue here - file uploaded, block displayed with working link, but without the file name. It looks like an error when parsing data from the upload result.

**Comment by PINHOf** [comment]
I had the same issue, but by taking a look at the plugin JS file, I found out that the documentation is wrong. Instead of filling `name` you should be filling `title`.

So, your output must be something like:
```
{
	'success' => 1,
	'file' => 
	[
		'url' => '...',
		'title' => '...',
		'extension' => '...',
		'size' => '...'
	],
}
```

**Comment by neSpecc** [comment]
Yep, something breaked. I'll take a look.
