### ISSUE TITLE
attachment doesn't show in read mode, only shows in edit mode

### ISSUE THREAD

**Issue by minhluudinh** [editor-js/attaches#72]
I am using codex docs and want to add file attachment to editorjs, the attachment doesn't show in read mode
![Screenshot_20221118_154205](https://user-images.githubusercontent.com/63277221/225680857-bf6bc865-6797-4985-8833-8f496e39daed.png)
![2](https://user-images.githubusercontent.com/63277221/225680992-3125788d-0ef1-4dcb-8ef7-3d374d9bfb7a.png)
![3](https://user-images.githubusercontent.com/63277221/225681174-6665a9c7-2e9b-48e4-82d3-21d77a91991f.png)

**Comment by neSpecc** [comment]
This issue is related to the CodeX Docs repo. See https://github.com/codex-team/codex.docs/issues/297
